### ISSUE TITLE
[TODO] Speed up OpenPose inferencing

### ISSUE THREAD

**Issue by zsdonghao** [tensorlayer/hyperpose#54]
- [x] TensorRT
- [x] MobileNet
- [x] Batch inferencing
- [x] Streaming pipeline
- [ ] Fast post-processing
  - [x] max pooling with cudnn
  - [ ] resize with npp
- [ ] Compiler optimization
  - [x] build with `-ffast-math`
  - [ ] build with openmp enabled

**Comment by lgarithm** [comment]
The inference time for a single image is

t = t0 + t1 + t2

where

- t0 is the pre-process time, including input image, resize it to fix the network input
- t1 is the time it spends on the network forwarding
- t2 is the post processing (#56)

and the FPS is 

1 / t = 1 / (t0 + t1 + t2) < min(1 / t0, 1 / t1, 1 / t2)

**Comment by lgarithm** [comment]
hao28, gtx1050ti, 368x432

```
        summary of tracer_ctx_t::global (32.636205s)
--------------------------------------------------------------------------------
   count      cumulative (s)               %       mean (ms)    call site
--------------------------------------------------------------------------------
       1           32.636019          100.00      32636.0194    main
       1           32.635952          100.00      32635.9518    inference
       1           32.262723           98.86      32262.7234    create_engine
       4            0.353575            1.08         88.3938    inference one
       4            0.162596            0.50         40.6490    run paf_process
       4            0.162569            0.50         40.6423    operator()
       4            0.145614            0.45         36.4035    run tensorRT
       4            0.145556            0.45         36.3891    execute
       4            0.142615            0.44         35.6538    context->execute
       4            0.119082            0.36         29.7705    get_peak_map
       4            0.053361            0.16         13.3402    same_max_pool_3x3
       4            0.047612            0.15         11.9031    smooth
       8            0.026306            0.08          3.2882    resize_area
       4            0.024099            0.07          6.0248    draw_results
       4            0.016997            0.05          4.2491    operator()::internal
      10            0.016923            0.05          1.6923    tensor_t
       4            0.015271            0.05          3.8178    select_peaks
       4            0.014158            0.04          3.5394    inplace_select_peaks
       4            0.001877            0.01          0.4693    copy input from host
       1            0.001852            0.01          1.8521    createBuffers_
       3            0.001787            0.01          0.5957    safeCudaMalloc
       4            0.001779            0.01          0.4448    fromHost
       4            0.001147            0.00          0.2868    getAllConnections
       4            0.000945            0.00          0.2363    copy output to host
       8            0.000883            0.00          0.1104    toHost
       4            0.000361            0.00          0.0903    getHumans
       4            0.000072            0.00          0.0180    generate output
```

**Comment by PrinceP** [comment]
Hi @lgarithm ,
I was noting the performance numbers for the VggTiny and Hao28. 
![screenshot from 2018-11-14 14-03-02](https://user-images.githubusercontent.com/10251537/48469998-3f140000-e816-11e8-90b7-f09ecc7e098f.png)

Are these numbers as per the repo?
You are reporting 38 fps (0.026 sec/image) for 1050 GPU.

**Comment by lgarithm** [comment]
@PrinceP I don't quite understand your question.
My above post was based on one snapshot in the repository, 
it was running on a DELL G5 laptop with gtx1050 ti.

**Comment by PrinceP** [comment]
@lgarithm I have noted the numbers on the python code of uff-runner.py on a K80.
